# Generated by Django 2.0.2 on 2018-02-12 19:41

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(null=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
